buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.1'
        classpath 'com.diffplug.spotless:spotless-plugin-gradle:8.4.0'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.diffplug.spotless'

repositories {
    google()
    mavenCentral()
    maven { url='https://jitpack.io'}
}

android {
    namespace 'eu.siacs.conversations'
    compileSdk 36

    defaultConfig {
        minSdkVersion 23
        versionCode 42177
        versionName "2.20.0"
        applicationId "eu.siacs.conversations"
        resValue "string", "applicationId", applicationId
        resValue "string", "app_name", "Conversations"
    }

    signingConfigs {
        release {
            def propsFile = file('signing.properties')
            if (propsFile.canRead()) {
                def props = new Properties()
                props.load(new FileInputStream(propsFile))
                storeFile file(props['keystore'])
                storePassword props['keystore.password']
                keyAlias props['keystore.alias']
                keyPassword props['key.password']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true
        resValues true
    }

    flavorDimensions += ["mode", "distribution"]
    productFlavors {
        conversations { 
            dimension "mode" 
            resValue "string", "app_name", "Conversations"
        }
        free { dimension "distribution" }
    }
}

dependencies {
    // ПОДКЛЮЧАЕМ ВСЕ БИБЛИОТЕКИ ИЗ ПАПКИ LIBS
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.emoji2:emoji2:1.6.0'
    implementation 'androidx.viewpager:viewpager:1.1.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0'
    
    freeImplementation 'androidx.emoji2:emoji2-bundled:1.6.0'
    
    implementation 'com.google.guava:guava:33.6.0-android'
    implementation 'org.jxmpp:jxmpp-jid:1.1.0'
    implementation 'org.minidns:minidns-client:1.1.1'
    implementation 'org.whispersystems:signal-protocol-java:2.6.2'
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
}
